default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: postgres
  password: 1234
  timeout: 5000

development:
  <<: *default
  database: zimple_pr_development

test: &test
  <<: *default
  database: zimple_pr_test

production:
  <<: *default
  database: zimple_pr_production
